set(SOURCE_FILES
    stat_bench/bench/benchmark_case_info_test.cpp
    stat_bench/clock/duration_test.cpp
    stat_bench/clock/monotone_clock_impl_test.cpp
    stat_bench/clock/monotone_clock_test.cpp
    stat_bench/clock/monotone_time_point_test.cpp
    stat_bench/clock/stop_watch_test.cpp
    stat_bench/clock/system_clock_test.cpp
)
