#include "stat_bench/clock/duration_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "stat_bench/clock/monotone_clock_impl_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "stat_bench/clock/monotone_clock_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "stat_bench/clock/monotone_time_point_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "stat_bench/clock/stop_watch_test.cpp"  // NOLINT(bugprone-suspicious-include)
