set(SOURCE_FILES
    bench_impl/benchmark_case_registry.cpp
    bench_impl/benchmark_group.cpp
    bench_impl/invocation_context_registry.cpp
    clock/monotone_clock_impl.cpp
    filters/composed_filter.cpp
    filters/glob_filter.cpp
    filters/regex_filter.cpp
    measurer/determine_iterations.cpp
    measurer/determine_warming_up_samples.cpp
    measurer/mean_processing_time_measurer.cpp
    measurer/measure_once.cpp
    measurer/processing_time_measurer.cpp
    param/parameter_generator.cpp
    reporter/cdf_line_plot_reporter.cpp
    reporter/console_reporter.cpp
    reporter/data_file_helper.cpp
    reporter/jinja_renderer.cpp
    reporter/json_reporter.cpp
    reporter/msgpack_reporter.cpp
    reporter/simple_line_plot_reporter.cpp
    reporter/violin_plot_reporter.cpp
    runner/command_line_parser.cpp
    runner/runner.cpp
    stat/calc_stat.cpp
    stat/statistics.cpp
    use_pointer.cpp
    util/check_glob_pattern.cpp
    util/escape_for_html.cpp
    util/prepare_directory.cpp
    util/sync_barrier.cpp
)
